Feature/handle failure
ONSdigital/dp-static-file-publisher pull request #20
Opened 2021-02-24 17:10 UTC by cadmiumcat

### What
This PR ensures that `dp-static-file-uploader` can deal with failure scenarios.
The status of a `download variant` is set to `failed_publish` (via a `PUT` request to the image api) when the handler fails to:
- get the vault key,
- decrypt the file from private S3 bucket, or
- upload the image variant to public S3 bucket

Similarly, if the `image` status is set to `failed_publish` if it's unable to
- get a particular variant
- update the status of a variant

#### Other things

- Improved readability of assertions using `ShouldHaveLength`
- Updated dependencies

### How to review

- Does the logic for the statuses make sense? 
- Check that tests and audit succeed 

### Who can review

Anyone

2021-02-25 10:46 UTC, jessjenkins requested changes
As well as the two other comments I've made, the `event/handler_test` needs to be updated to test that the failures are being sent to the API (or not) when the scenario happens. Take a look at an example for [one of the failure scenarios in the image-importer equivalent](https://github.com/ONSdigital/dp-image-importer/commit/17178c20c0a8a7cb57cebdf7df63fecae4740e6f#diff-a180d0f817c32115b9a520951f74b0fca6cc080dd71714f658820f69d540e59cR468) to see what I mean.

2021-02-25 10:46 UTC, jessjenkins commented on event/handler.go
> +		h.setImageStatusToFailed(ctx, event.ImageID, "error getting image variant from API")
I'd probably add more context to the error text, eg.
```suggestion
		h.setImageStatusToFailed(ctx, event.ImageID, fmt.Sprintf("error getting image variant '%s' from API", event.ImageVariant))
```

2021-02-25 10:46 UTC, jessjenkins commented on event/handler.go
> +		h.setImageStatusToFailed(ctx, event.ImageID, "error putting updated image variant to API")
Extra context needed on which variant couldn't be updated
```suggestion
		h.setImageStatusToFailed(ctx, event.ImageID, fmt.Sprintf("error putting updated image variant '%s' to API", event.ImageVariant))
```

2021-02-26 12:33 UTC, cadmiumcat commented
> As well as the two other comments I've made, the `event/handler_test` needs to be updated to test that the failures are being sent to the API (or not) when the scenario happens. Take a look at an example for [one of the failure scenarios in the image-importer equivalent](https://github.com/ONSdigital/dp-image-importer/commit/17178c20c0a8a7cb57cebdf7df63fecae4740e6f#diff-a180d0f817c32115b9a520951f74b0fca6cc080dd71714f658820f69d540e59cR468) to see what I mean.

Thanks 🙂 - I've added some tests. I _think_ they make sense but I can't help but feel that I've missed out at least a scenario

2021-02-26 13:52 UTC, jessjenkins commented on event/handler_test.go
> +			mockVariantAPIFail := &mock.ImageAPIClientMock{
It's still a mock for the Image API so the original variable name was fine :-)

2021-02-26 13:53 UTC, jessjenkins commented on event/handler_test.go
> +			mockVariantAPIFail := &mock.ImageAPIClientMock{
Previous name of var fine
```suggestion
			mockImageAPIFail := &mock.ImageAPIClientMock{
```

2021-02-26 14:01 UTC, jessjenkins commented on event/handler_test.go
> +				So(mockImageAPI.PutDownloadVariantCalls(), ShouldHaveLength, 1)
Not an issue with this line (it's just the closest place I can put it) but after this Convey block, you could probably test that the image API's `Image` endpoints aren't called when everything is good. So something like…
```
Convey("The Image resource isn't modified directly", func() {
    So(mockImageAPI.GetImageCalls(), ShouldBeEmpty)
    So(mockImageAPI.PutImageCalls(), ShouldBeEmpty)
}
```

2021-02-26 14:02 UTC, jessjenkins commented on event/handler_test.go
> +				So(mockImageAPI.PutDownloadVariantCalls(), ShouldHaveLength, 1)
Again, as above, Not an issue with this line (it's just the closest place I can put it) but after this Convey block, you could probably test that the image API's `Image` endpoints aren't called when everything is good. So something like…
```
Convey("The Image resource isn't modified directly", func() {
    So(mockImageAPI.GetImageCalls(), ShouldBeEmpty)
    So(mockImageAPI.PutImageCalls(), ShouldBeEmpty)
}
```

2021-03-03 17:53 UTC, jessjenkins approved these changes

2021-03-04 17:42 UTC, merged